timezone: Europe/Oslo
title: LunarWatcher
email: zoe.i2k1@gmail.com
github: LunarWatcher
twitter: OliviaZoe0
rss: /feed.xml
stackoverflow: "6296561"
deviantart: oliviazoe0
discord-server: "bjZD42j"
discord-username: Olivia#0740
keybase: oliviazoe0

name: LunarWatcher

markdown: kramdown
highlighter: rouge

kramdown: 
    input: GFM
    hard_wrap: false
    highlight: true
    auto_ids: true

theme: minima

baseurl: ""
sass:
    sass_dir: assets/css
    style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - "jekyll-paginate"

paginate_path: "/posts/page/:num/"
paginate: 15

