timezone: Europe/Oslo
title: LunarWatcher
email: zoe.i2k1@gmail.com
github: LunarWatcher
twitter: OliviaZoe0
rss: /feed.xml
stackoverflow: "6296561"
deviantart: oliviazoe0
discord-server: https://discordapp.com/invite/WTJ8g3v
discord-username: Olivia#0740

name: LunarWatcher

markdown: kramdown
highlighter: rouge

kramdown: 
    input: GFM
    hard_wrap: false
    highlight: true
    auto_ids: true

theme: minima

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]

baseurl: ""
sass:
    sass_dir: assets/css
    style: compressed

plugins:
  - jekyll-feed
