baseURL: https://lunarwatcher.github.io
languageCode: en-GB
title: Olivia's blog
publishDir: public
permalinks:
  posts: /posts/:year/:month/:day/:slug

uglyurls: true
pygmentsUseClasses: true

markup:
  enableEmoji: true
  goldmark:
    extensions:
      linkify: true
      typographer: false
      footnote: true
    renderer:
      unsafe: true
      footnoteAnchorPrefix: ""
      footnoteReturnLinkContents: "^"
  highlight:
    style: emacs
  tableOfContents:
    endLevel: 6
    startLevel: 2

outputs:
  taxonomy: ["HTML"]
  term: ["HTML"]
  page: ["HTML"]
  home: ["HTML"]

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

taxonomies:
  tag: tags
  series: series

# There has to be a better way to do this
menu:
  main:
  - identifier: Home
    name: Home
    url: "/"
    weight: 1
  - identifier: Blog
    name: Blog
    url: "/posts/"
    weight: 2
  - identifier: Tags
    name: Tags
    url: "/tags.html"
    weight: 3
  - identifier: TIL
    name: TIL
    url: "/til/"
    weight: 4
  - identifier: Contact me
    name: Contact me
    url: "/contact.html"
    weight: 5
    # In retrospect, this feels fucking moronic
    # You know what the navbar needs? A dropdown.
    # Have fun, future future me
  - identifier: Pages
    name: Other pages
    url: "/pages.html"
    weight: 6


params:
  discord: y3vd2vAYru
  discord_user: oliviawolfie
  github: LunarWatcher
  gpg-signature: "2CE6 6B15 2ED5 6C24 C6A9 C71E 76C0 735B CD18 3F71"
  email_proxy: "https://en.wikipedia.org/wiki/Special:EmailUser/OliviaWolfie"
