baseURL: https://lunarwatcher.github.io
languageCode: en-GB
title: Olivia's blog
publishDir: public
permalinks:
  posts: /posts/:year/:month/:day/:slug

uglyurls: true
pygmentsUseClasses: true

markup:
  enableEmoji: true
  goldmark:
    extensions:
      linkify: true
      typographer: false
      footnote: true
    renderer:
      unsafe: true
      footnoteAnchorPrefix: ""
      footnoteReturnLinkContents: "^"
  highlight:
    style: emacs
  tableOfContents:
    endLevel: 6
    startLevel: 2

outputs:
  taxonomy: ["HTML"]
  page: ["HTML"]
  home: ["HTML"]

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

taxonomies:
  tag: tags
  series: series

menu:
  main:
  - identifier: Home
    name: Home
    url: "/"
    weight: 1
  - identifier: Blog
    name: Blog
    url: "/posts/"
    weight: 2
  - identifier: Tags
    name: Tags
    url: "/tags.html"
    weight: 3
  - identifier: TIL
    name: TIL
    url: "/til/"
    weight: 4
  - identifier: Pages
    name: Other pages
    url: "/pages.html"
    weight: 5


params:
  discord: y3vd2vAYru
  discord_user: oliviawolfie
  github: LunarWatcher
  email_proxy: "https://en.wikipedia.org/wiki/Special:EmailUser/OliviaWolfie"
  tags:
    c++: Posts and notes about the C++ language. This description pretty much only exists so I can test whether or not my config.yaml-based system for descriptions work :)
