baseURL: https://lunarwatcher.github.io
disablePathToLower: true
languageCode: en-us
title: LunarWatcher
publishDir: public
permalinks:
  posts: /posts/:year/:month/:day/:slug

uglyurls: true
pygmentsUseClasses: true

markup:
  goldmark:
    extensions:
      linkify: false
  highlight: 
    style: emacs 
  tableOfContents: 
    endLevel: 6
    startLevel: 1

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

menu:
  main:
  - identifier: Home 
    name: Home 
    url: "/"
    weight: -110
  - identifier: Blog
    name: Blog
    url: "/posts/"
    weight: -100
  - identifier: Emoji reference 
    name: Emoji reference
    url: "/emojis.html"
    weight: -90
