baseURL: https://lunarwatcher.github.io
disablePathToLower: true
languageCode: en-us
title: LunarWatcher
publishDir: public
permalinks:
  posts: /posts/:year/:month/:day/:slug

uglyurls: true
pygmentsUseClasses: true
disablePathToLower: false

markup:
  goldmark:
    extensions:
      linkify: true
    renderer:
      unsafe: true
  highlight: 
    style: emacs 
  tableOfContents: 
    endLevel: 6
    startLevel: 2

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

taxonomies:
  tag: tags

menu:
  main:
  - identifier: Home 
    name: Home 
    url: "/"
    weight: 1
  - identifier: Blog
    name: Blog
    url: "/posts/"
    weight: 2
  - identifier: Tags
    name: Tags
    url: "/tags.html"
    weight: 3
  - identifier: Notes
    name: Notes
    url: "/notes/"
    weight: 4
  - identifier: Emoji reference 
    name: Emoji reference
    url: "/emojis.html"
    weight: 5

params:
  discord: bJgdwZJYXY
  discord_user: Olivia#0740
  twitter: OliviaZoe0
  github: LunarWatcher
  deviantart: oliviazoe0
  tags:
    c++: Posts and notes about the C++ language. This description pretty much only exists so I can test whether or not my config.yaml-based system for descriptions work :)
