baseURL: https://lunarwatcher.github.io
languageCode: en-GB
title: Olivia's blog
publishDir: public
permalinks:
  posts: /posts/:year/:month/:day/:slug

uglyurls: true
pygmentsUseClasses: true

markup:
  enableEmoji: true
  goldmark:
    extensions:
      linkify: true
      typographer: false
      footnote: true
    renderer:
      unsafe: true
      footnoteAnchorPrefix: ""
      footnoteReturnLinkContents: "^"
  highlight:
    style: emacs
  tableOfContents:
    endLevel: 6
    startLevel: 2

outputs:
  taxonomy: ["HTML"]
  taxonomyTerm: ["HTML"]
  page: ["HTML"]
  home: ["HTML"]

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

taxonomies:
  tag: tags
  series: series

menu:
  main:
  - identifier: Home
    name: Home
    url: "/"
    weight: 1
  - identifier: Blog
    name: Blog
    url: "/posts/"
    weight: 2
  - identifier: Tags
    name: Tags
    url: "/tags.html"
    weight: 3
  - identifier: TIL
    name: TIL
    url: "/til/"
    weight: 4
  - identifier: Pages
    name: Other pages
    url: "/pages.html"
    weight: 5


params:
  discord: y3vd2vAYru
  discord_user: oliviawolfie
  github: LunarWatcher
  email_proxy: "https://en.wikipedia.org/wiki/Special:EmailUser/OliviaWolfie"
  tags:
    c++: Posts and notes about the C++ language. This description pretty much only exists so I can test whether or not my config.yaml-based system for descriptions work :)
    hacktoberfest: Posts about [Hacktoberfest](https://hacktoberfest.digitalocean.com/), a yearly event centered around contributing to open-source.
  projects:
    - name: This website :)
      languages: [HTML, SCSS, JavaScript, Go templates]
      state: ad
      link: https://github.com/LunarWatcher/lunarwatcher.github.io
      license: See repository
      description: |
        My website (you're here!), where I add whatever I feel like adding, and periodically torture myself with aligning divs in flexboxes (including the flexbox you're reading this in right now).
    - name: Dotfiles
      languages: [Vimscript, "vim9script (soon:tm:)", makefiles, vim snippets]
      state: ad
      link: https://github.com/LunarWatcher/dotfiles
      license: unlicense
      description: A collection of dotfiles I use. Expands whenever I see a need to.
    - name: Genesis
      languages: [C++, GLSL, CMake]
      state: ad
      link: https://github.com/lunarwatcher/Genesis
      license: MIT
      description: |
        WIP game with currently no gameplay, because I wanted to do something with shaders.
    - name: Dragon
      languages: [Python]
      state: ad
      link: https://github.com/LunarWatcher/Dragon
      license: MIT
      description: |
        Dragon is a bot to handle the "grunt work" of edits on Stack Overflow. This primarily means stuff that can be done with little effort,
        but that's time-consuming due to the quantity.
    - name: upm
      languages: [C++, CMake, Shell, Lua]
      state: ad
      link: https://github.com/LunarWatcher/upm
      license: MIT
      description: |
        upm is a package manager meant to keep stuff up to date. Particularly useful on distros (*cough cough Debian and derivatives*) where the repos are
        severely out of date, and minimum version dependencies have passed the unnecessarily old version in the repos.
    - name: Spaceport
      languages: [C++, CMake, Lua]
      state: ad
      link: https://github.com/LunarWatcher/Spaceport
      license: MIT
      description: |
        Spaceport is a homelab dashboard, primarily aimed at monitoring and navigation.
    - name: Skye
      languages: [Vimscript, Vim9script, C++]
      state: sp
      license: MIT
      link: https://github.com/LunarWatcher/Skye.vim
      description: |
        An attempt at integrating some GitHub support into Vim, because nothing quite says masochism like Vimscript and C++ interop with web requests.

        Vim and terminals already have plenty of support for Git, but GitHub support in Vim is scarce.
    - name: doesnotfail2ban
      link: https://github.com/LunarWatcher/doesnotfail2ban
      state: upc
      languages: [C++]
      license: MIT
      description: |
        fail2ban but functional, fast, and reliable, with a higher focus on statistics and data
    - name: Auto-pairs
      languages: [Vimscript]
      state: ma
      license: MIT
      link: https://github.com/LunarWatcher/auto-pairs
      description: |
        Initially a fork from [jiangmiao/auto-pairs](//github.com/jiangmiao/auto-pairs), but that today consists of heavy improvements to the original.

        With several huge feature updates, the project aims to keep auto-pairs alive, even if its original author disappeared without arranging
        future maintenance.
    - name: Dawn
      languages: [Vimscript]
      state: ma
      license: See repository (MIT + unlicense)
      link: https://github.com/LunarWatcher/Dawn
      description: |
        Generates projects in Vim, similar to what an IDE would, but with complete freedom wrt. what's generated.

        There's built-in structures for (my) C++ CMake structure, and a standard Vimscript structure.
        The repo is open for additional templates, however, and users can additionally customize existing templates,
        or add completely new ones.
    - name: DiscordWebhooks.cpp
      link: https://github.com/LunarWatcher/DiscordWebhooks.cpp
      state: po
      languages: [C++]
      license: MIT
      description: |
        Reads RSS feeds and sends updates to channels through webhooks.

        Self-hosted, bot-less option to various RSS bots. (Built because one of said bots were
        far too flaky, prompting me to make one instead of hoping it works and doesn't have another
        multi-day streak of downtime)
    - name: Taskranger
      state: de
      license: MIT
      link: https://github.com/LunarWatcher/Taskranger
      description: |
        An attempt at making an alternative to Taskwarrior, but that eventually died because my needs changed, along with my managing needs.
      languages:
        - C++
  projectstate:
    # vvvv commitment right here
    ad:
      name: Active
      span: projact
      desc: Projects in active development
    sp:
      name: Side-project
      span: projside
      desc: Side-projects that are in active development, but that aren't in as active development as main projects.
    ma:
      name: Maintained
      span: projmain
      desc: Projects that are being maintained, but that aren't under active development. Primarily applies the projects where ideas have dried up.
    in:
      name: Inactive
      span: projin
      desc: Projects that are currently not receiving any attention.
    po:
      name: Patches only
      span: projpat
      desc: Projects only receiving patches.
    ab:
      name: Abandoned
      span: projaban
      desc: Projects that have been abandoned intentionally
    de:
      name: Dead
      span: projdead
      desc: Projects that have been abandoned due to circumstance, including (but not limited to) loss of interest, loss of need, or my focus being pulled elsewhere.
    upc:
      name: Upcoming
      span: projupc
      desc: Upcoming projects; stay tuned! The repos for these projects exist, but have not been made public
