name: Deploy pages
on:
  push:
    branches: [ source ]
  workflow_dispatch:

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        submodules: true
      - uses: actions/setup-python@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true
      - name: Run hugo and commit
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email actions@github.com
          git clone -b master https://github.com/lunarwatcher/lunarwatcher.github.io public
          hugo --minify
          cd public && git add -A && git commit -m "Deploy changes" && git push origin master
