name: Deploy pages
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/checkout@v2
        with:
          repository: LunarWatcher/LunarWatcher.github.io
          ref: deployment
          path: public
      - uses: actions/setup-python@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Run hugo and commit
        shell: bash
        run: |
          mkdir public 
          hugo --minify
          cd public && git init && git add -A
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -m "Deploy changes for ${GITHUB_SHA}" && git push origin deployment --force
