name: Deploy pages
on:
  push:
    branches: [ source ]
  workflow_dispatch:

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/checkout@v2
        with:
          repository: LunarWatcher/LunarWatcher.github.io
          ref: master
          path: public
      - uses: actions/setup-python@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true
      - name: Run hugo and commit
        shell: bash
        run: |
          pwd
          cd public && git rm -rf . && cd ..
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          hugo --minify
          cd public && git add -A && git commit -m "Deploy changes" && git push origin master
